### ISSUE TITLE
Displaying bootstrap values

### ISSUE THREAD

**Issue by Kevin-BioDF** [lipme/vue-phylogram#2]
Hello again Ludo,

I was wondering if it is currently possible to display the bootstrap values on the tree? And if so, what is the format that the bootstrap values should be in?

Thanks again! 

(Sorry for opening up another issue - should I perhaps contact you directly through email or something if I have more questions about using `vue-phylogram`?)

**Comment by lcottret** [comment]
Hi Kevin !

It's the good place for this kind of questions ! For the moment, unfortunatelyn it's not possible to display bootstrap values... I note it as suggestion for later.

Best regards,
Ludo

**Comment by Kevin-BioDF** [comment]
I see, thanks for letting me know!

**Comment by lipme** [comment]
Hi Kevin,

It's now possible to display support values with the version 3.1.1 of vue-phylogram. Please read the README.md for more details.

Regards,
Ludo

**Comment by Kevin-BioDF** [comment]
Hi Ludo,

Great, thank you for the update!

**Comment by Kevin-BioDF** [comment]
Hi Ludo,

I would like to clarify if the version is 3.1.1? It seems that the latest release version is 3.0.1 (https://github.com/lipme/vue-phylogram/releases). And from the latest documentation I cannot find how to enable it do display on the tree and if it will parse the Newick format automatically into the appropriate format with the `support` key in the node.  

Thanks for any clarification,

**Comment by lcottret** [comment]
Hi Kevin,

Oh, I fixed it. Please consider the version 3.1.2 on github or in npm. In the README.md, there is a section "Display support values".

Ludo
