### ISSUE TITLE
Select branches/node

### ISSUE THREAD

**Issue by fraser-combe** [lipme/vue-phylogram#5]
How is the select a branch or node initiated.
My current v-card contains
<VuePhylogram
              :newick="newick"
              align-labels
              :display-inner-nodes="true"
              :branch-styles="branchStyles"
              :default-colors="defaultColors"
            ></VuePhylogram>
I am using the tutorial to find out how to select the nodes or branches and color by a specific color with a simple nexus file and hope you can help, maybe I missed something in the tutorial?

**Comment by lipme** [comment]
Hi !
Thanks for using vue-phylogram. I think that a piece of your message is missing (what is the content of your v-card ?). 
To select one node and the corresponding sub-tree and deselect when you click outside, you can do somthing like this:

```html
<phylogram @click-node="selectNode" @click-outside="clickOutside" />
```
```javascript
methods: {
    clickNodeFn (e, node) {
      this.$refs.phylo.deselectAll()
      this.$refs.phylo.selectNode(node)
    },
    clickOutside () {
      this.$refs.phylo.deselectAll()
    },
...
```

I hope that that answers your question.

Ludo

**Comment by fraser-combe** [comment]
Apologies I didnt attach v-card text. Your suggestion worked thank you! I just swapped 
@click-node="selectNode" with @click-node="clickNodeFn" and added ref="phylo"
For reference, and help to others my v-card is:

`<VuePhylogram
            ref="phylo"
            id="VuePhylogram"
            :newick="newick"
            align-labels
            :display-inner-nodes="true"
            :branch-styles="branchStyles"
            :default-colors="defaultColors"
            :node-styles="nodeStyles"
            @click-node="clickNode"
            @click-outside="clickOutside"
            @select-nodes="selectNodes"
            @hover-node="hoverNodeFn"
            @hover-label="hoverNodeFn"
          ></VuePhylogram>`

and methods:
`methods: {
    clickNode (e, node) {
      this.$refs.phylo.deselectAll()
      this.$refs.phylo.selectNode(node)
    },
    clickOutside () {
      this.$refs.phylo.deselectAll()
    },
    selectNodes (nodes) {
      this.$emit('select-node', nodes)
    },
    hoverNodeFn (e, node) {
      this.nodeInfo = { id: node.data.id, name: node.data.name }
    },`

**Comment by fraser-combe** [comment]
Apologies I didnt attach v-card text. Your suggestion worked thank you! I just swapped 
@click-node="selectNode" with @click-node="clickNodeFn" and added ref="phylo"
Here is my working v-card, and help to others:
```
<VuePhylogram
            ref="phylo"
            id="VuePhylogram"
            :newick="newick"
            align-labels
            :display-inner-nodes="true"
            :branch-styles="branchStyles"
            :default-colors="defaultColors"
            :node-styles="nodeStyles"
            @click-node="clickNode"
            @click-outside="clickOutside"
            @select-nodes="selectNodes"
            @hover-node="hoverNodeFn"
            @hover-label="hoverNodeFn"
          ></VuePhylogram>
```  
and methods:
```
methods: {
    clickNode (e, node) {
      this.$refs.phylo.deselectAll()
      this.$refs.phylo.selectNode(node)
    },
    clickOutside () {
      this.$refs.phylo.deselectAll()
    },
    selectNodes (nodes) {
      this.$emit('select-node', nodes)
    },
    hoverNodeFn (e, node) {
      this.nodeInfo = { id: node.data.id, name: node.data.name }
    },
```
