### ISSUE TITLE
margin between rectangles

### ISSUE THREAD

**Issue by neriaaa46** [lipme/vue-phylogram#8]
Two questions: 
1. There is options to make margin between rectangles ? 
2. if I decide use circles instead rectangles there is options to color the circles like the rectangles, when I tried the default color was black and I didn't succeed to change the colors by the glyphs props.

**Comment by lipme** [comment]
1. Not for the moment, but it's a good suggestion :-).
2. Please use the last version of vue-phylogram, this bug has been fixed recently.

**Comment by neriaaa46** [comment]
The margins between rectangles (or circles) are very important because when dividing leaves into groups according to colors and rectangles it is very difficult when the rectangles are very close.

If this suggestion will be in the next version, I'd love to know about it

**Comment by lipme** [comment]
Hi @neriaaa46 !

In the last version of vue-phylogram (3.4.2), you can now add margins between glyphs by using the props glyph-margin.
Example : 
```html
<Phylogram :inputTree="tree" :glyphs="glyphs" glyph-margin="5">
```
